import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import Header from '../components/header'
//import '../styles/landing.css'

const inter = Inter({ subsets: ['latin'] })





function Motd(){
  return(
    <div className='motd'>
      <h2 className='motdLabel'>MEAL OF THE DAY</h2>
      <div className='motdflex'>
      <div className='theMeal'>
        <div className='leftmotd'>
          <h1 className='foodName'>Salted egg rice</h1>
         
          <h4>PRICE:<span>     </span>  $10</h4>
          <Link href='/order'><button className='placeOrd'>PLACE ORDER</button></Link>
        </div>
        <Image className='motdImg' src='/sefr.png' alt='motd'
          width={620} height={620} priority/>
      </div>
      </div>
    </div>
  )
}

function Dishes(){
  return(
    <div className='dishes'>
      <h2>DISHES</h2>
      <div className='gridwrap'>
      <div className='dishgrid'>
        <div className='dishcard'>
        <Image className='dishImg' src='/egusi-and-akpu.jpg' alt='local'
          width={210} height={210} priority/>
          <h3>LOCAL</h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, 
            sed do eiusmod tempor incididunt ut labore et dolore magna 
            aliqua. Ut enim ad minim veniam, 
            quis nostrud exercitation ullamco laboris nisi</p>
            <button className='see'>SEE ITEMS</button>
        </div>
        <div className='dishcard'>
        <Image className='dishImg' src='/intl.jpg' alt='international'
          width={210} height={210} priority/>
          <h3>INTERNATIONAL</h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, 
            sed do eiusmod tempor incididunt ut labore et dolore magna 
            aliqua. Ut enim ad minim veniam, 
            quis nostrud exercitation ullamco laboris nisi </p>
            <button className='see'>SEE ITEMS</button>
        </div>
      </div>
      </div>
    </div>
  )
}

function Mtc(){
  return(
    <div className='mtc'>
      <h2 className='mtclabel'>MEET OUR CHEF</h2>
      <div className='mtcwrap'>
      <div className='mtcgrid'>
        
        <div className='chefImg'> 
        <Image className='dishImg2' src='/ife.jpg' alt='international'
          width={380} height={380} priority/>
        </div>
            
        <div className='info'>
          <h3>Chef Ife Mayadenu</h3>
          <p>"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium
           doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore
            veritatis  sunt explicabo. Nemo enim
             sit amet, consectetur, 
               adipisci velit, sed quia non numquam</p>
        </div>
      </div>
      </div>
      <div className='swrap'>
         <Image className='social' src='/instagram.png' alt='ig'
          width={50} height={50} priority/>
          <Image className='social' src='/facebook.png' alt='fb'
          width={50} height={50} priority/>
          <Image className='social' src='/twitter.png' alt='tw'
          width={50} height={50} priority/>
          <Image className='social' src='/tiktok.png' alt='tk'
          width={50} height={50} priority/>
      </div>
    </div>
  )
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Mutanos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        
      </Head>
      <main>
        <Header/>
        <Motd/>
        <Dishes/>
        <Mtc/>


      </main>
    </>
  )
}
